apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: app-name
    - name: build-image
    - name: repo-url
    - name: ibmcloud-api-key
    - name: ibmcloud-project-id
    - name: branch
      default: master
  tasks:
    - name: printparams
      taskRef:
        name: echo
      params:
      - name: message
        value: "Deploying $(params.ibmcloud-api-key) branch of $(params.repo-url) ..."

    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup
      runAfter:
        - printparams

    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init      
        
    - name: npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: npm
      runAfter:
        - clone
        
    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: jasmine
      runAfter:
        - npminstall

    - name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
      - name: IMAGE
        value: "$(params.build-image)"
      runAfter:
        - tests

    - name: login
      taskRef:
        name: ibmcloud
        # kind: ClusterTask
      params:
      - name: ARGS
        value: 
          - "login"
          - "--apikey=$(params.ibmcloud-api-key)"
      runAfter:
        - build
