apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: app-name
    - name: build-image
    - name: repo-url
    - name: ibmcloud-api-key
    - name: ibmcloud-region
      default: us-south
    - name: ibmcloud-project-id
    - name: branch
      default: master
  tasks:
    - name: login1
      taskRef:
        name: ibmcloud
      params:
      - name: ARGS
        value: 
          - "login"
          - "--apikey=$(params.ibmcloud-api-key)"
          - "-g"
          - "production"
          - "-r"
          - "$(params.ibmcloud-region)"
      # runAfter:
      #   - tests

    - name: cr-login1
        value: 
          - "cr"
          - "login"
          - "--apikey=$(params.ibmcloud-api-key)"
          - "-g"
          - "production"
          - "-r"
          - "$(params.ibmcloud-region)"
      runAfter:
        - login1

    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup
      runAfter:
        - cr-login1
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init      
        
    - name: npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: npm
      runAfter:
        - clone
        
    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: jasmine
      runAfter:
        - npminstall

    - name: login
      taskRef:
        name: ibmcloud
      params:
      - name: ARGS
        value: 
          - "login"
          - "--apikey=$(params.ibmcloud-api-key)"
          - "-g"
          - "production"
          - "-r"
          - "$(params.ibmcloud-region)"
      runAfter:
        - tests

    - name: cr-login
      taskRef:
        name: ibmcloud
      params:
      - name: ARGS
        value: 
          - "cr"
          - "login"
          - "--apikey=$(params.ibmcloud-api-key)"
          - "-g"
          - "production"
          - "-r"
          - "$(params.ibmcloud-region)"
      runAfter:
        - login
    # - name: cr-login
    #   workspaces:
    #     - name: source
    #       workspace: pipeline-workspace          
    #   taskRef:
    #     name: ibm-cr-login
    #   runAfter:
    #     - login
    # - name: build
    #   taskRef:
    #     name: docker-build
    #   params:
    #   - name: image
    #     value: "us.icr.io/sn-labs-muhammady/tax-calculator"
    #   - name: build_extra_args
    #     value: "-t"
    #   runAfter:
    #     - login

    # - name: deploy
    #   taskRef:
    #     name: ibmcloud
    #   params:
    #   - name: ARGS
    #     value: 
    #       - "ce"
    #       - "application"
    #       - "create"
    #       - "--name"
    #       - "tax-calculator"
    #       - "--image"
    #       - "us.icr.io/sn-labs-muhammady/tax-calculator"
    #       - "--registry-secret"
    #       - "icr-secret"
    #       - "--port"
    #       - "80"
    #   runAfter:
    #     - build

    - name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
      - name: IMAGE
        value: "$(params.build-image)"
      runAfter:
        - cr-login
