apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tc-pipeline-run
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: tc-pipeline
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
    - name: dockerconfig-ws
      secret:
        secretName: docker-reg-creds
  params:
    - name: repo-url
      value: "https://github.com/BobbyFranklin954/TaxCalculator"
    - name: branch
      value: "v2"
    - name: app-name
      value: "tax-calculator"
    - name: build-image
      value: "tax-calculator:latest"
